import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { isLikelyTermux } from './bionic.js';
import { home } from '../core/paths.js';

const BOOT_SCRIPT = 'start-termcrab';

export function bootScriptPath(): string {
  return path.join(os.homedir(), '.termux', 'boot', BOOT_SCRIPT);
}

/**
 * Termux:Boot script: wake-lock + start the TermCrab gateway on device boot.
 * This is our init system (Android has no systemd).
 */
export function installBootScript(binPath?: string): { path: string; created: boolean } {
  const dir = path.dirname(bootScriptPath());
  fs.mkdirSync(dir, { recursive: true });
  const bin = binPath || process.argv[1] || 'termcrab';
  const content = `#!/data/data/com.termux/files/usr/bin/bash
# TermCrab auto-start (generated by: termcrab boot install)
termux-wake-lock 2>/dev/null || true
export TCRAB_HOME="${home()}"
mkdir -p "${home()}/logs"
# restart the supervisor which owns the gateway
nohup "${process.execPath}" "${bin}" supervisor >> "${home()}/logs/boot.log" 2>&1 &
`;
  const p = bootScriptPath();
  const existed = fs.existsSync(p);
  fs.writeFileSync(p, content, { mode: 0o700 });
  return { path: p, created: !existed };
}

export function bootStatus(): { installed: boolean; path: string; termux: boolean } {
  return { installed: fs.existsSync(bootScriptPath()), path: bootScriptPath(), termux: isLikelyTermux() };
}

export function isTermux(): boolean {
  return isLikelyTermux();
}
