/**
 * Install TermCrab as a service, so it comes back after a reboot (32.4).
 *
 * Three platforms, one command, and no pretending: Android has no systemd, so
 * on Termux this delegates to the Termux:Boot script that already exists; on
 * Linux it writes a **systemd user unit** (no root, no sudo, and the file is
 * printed so you can read it before enabling it); on macOS a launchd agent.
 *
 * Everything is written under a directory that can be overridden
 * (`TCRAB_SERVICE_DIR`), which is how the test asserts the exact unit without
 * needing systemd in a sandbox — and how somebody can inspect the file before
 * letting an init system read it.
 */
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { home } from '../core/paths.js';
import { isTermux, installBootScript, bootStatus } from './boot.js';

export type ServicePlatform = 'systemd' | 'launchd' | 'termux';

export interface ServicePlan {
  platform: ServicePlatform;
  /** Absolute path of the unit/plist/script that is (or would be) written. */
  file: string;
  /** The exact contents. */
  content: string;
  /** The commands a human should run after installing (or has to, for Termux). */
  steps: string[];
  installed: boolean;
}

function serviceDir(): string {
  const override = process.env.TCRAB_SERVICE_DIR;
  if (override && override.trim()) return path.resolve(override);
  if (process.platform === 'darwin') return path.join(os.homedir(), 'Library', 'LaunchAgents');
  return path.join(os.homedir(), '.config', 'systemd', 'user');
}

export function detectServicePlatform(): ServicePlatform {
  if (isTermux()) return 'termux';
  if (process.platform === 'darwin') return 'launchd';
  return 'systemd';
}

/** The CLI entry point this install should run: whatever invoked us. */
function cliEntry(): string {
  return process.argv[1] || 'termcrab';
}

function systemdUnit(): string {
  const cli = cliEntry();
  return `# TermCrab gateway (generated by: termcrab service install)
# Read it, then enable it:
#   systemctl --user daemon-reload
#   systemctl --user enable --now termcrab
[Unit]
Description=TermCrab — personal AI agent (gateway + panel)
After=network-online.target

[Service]
Type=simple
WorkingDirectory=${home()}
Environment=TCRAB_HOME=${home()}
ExecStart=${process.execPath} ${cli} gateway
Restart=on-failure
RestartSec=3
# A phone agent should not fight the machine for memory.
Nice=5

[Install]
WantedBy=default.target
`;
}

function launchdPlist(): string {
  const cli = cliEntry();
  return `<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<!-- TermCrab gateway (generated by: termcrab service install) -->
<plist version="1.0">
<dict>
  <key>Label</key><string>dev.termcrab.gateway</string>
  <key>ProgramArguments</key>
  <array>
    <string>${process.execPath}</string>
    <string>${cli}</string>
    <string>gateway</string>
  </array>
  <key>EnvironmentVariables</key>
  <dict><key>TCRAB_HOME</key><string>${home()}</string></dict>
  <key>RunAtLoad</key><true/>
  <key>KeepAlive</key><true/>
  <key>StandardOutPath</key><string>${path.join(home(), 'logs', 'service.log')}</string>
  <key>StandardErrorPath</key><string>${path.join(home(), 'logs', 'service.err.log')}</string>
</dict>
</plist>
`;
}

export function servicePlan(): ServicePlan {
  const platform = detectServicePlatform();
  if (platform === 'termux') {
    const s = bootStatus();
    return {
      platform,
      file: s.path,
      content: '# Android has no systemd: this is the Termux:Boot script (termcrab boot install).\n',
      steps: [
        'install the Termux:Boot app once (F-Droid) and open it once',
        'termcrab boot install',
      ],
      installed: s.installed,
    };
  }
  const file = platform === 'launchd' ? path.join(serviceDir(), 'dev.termcrab.gateway.plist') : path.join(serviceDir(), 'termcrab.service');
  return {
    platform,
    file,
    content: platform === 'launchd' ? launchdPlist() : systemdUnit(),
    steps:
      platform === 'launchd'
        ? ['launchctl load -w ' + file]
        : ['systemctl --user daemon-reload', 'systemctl --user enable --now termcrab', 'systemctl --user status termcrab'],
    installed: fs.existsSync(file),
  };
}

export interface ServiceResult {
  ok: boolean;
  platform: ServicePlatform;
  file: string;
  installed: boolean;
  /** 'installed' | 'already installed' | 'removed' | 'not installed' | 'dry run' */
  action: string;
  steps: string[];
  error?: string;
}

/** Write the unit. Idempotent, and a no-op on Termux (where boot install is the path). */
export function installService(opts: { dryRun?: boolean; force?: boolean } = {}): ServiceResult {
  const plan = servicePlan();
  if (plan.platform === 'termux') {
    const r = installBootScript();
    return {
      ok: true,
      platform: plan.platform,
      file: r.path,
      installed: true,
      action: 'installed (Termux:Boot script — Android has no systemd)',
      steps: plan.steps,
    };
  }
  if (opts.dryRun) {
    return { ok: true, platform: plan.platform, file: plan.file, installed: plan.installed, action: 'dry run', steps: plan.steps };
  }
  const existed = fs.existsSync(plan.file);
  if (existed && !opts.force) {
    return { ok: true, platform: plan.platform, file: plan.file, installed: true, action: 'already installed', steps: plan.steps };
  }
  try {
    fs.mkdirSync(path.dirname(plan.file), { recursive: true });
    fs.writeFileSync(plan.file, plan.content, { mode: 0o644 });
    return { ok: true, platform: plan.platform, file: plan.file, installed: true, action: 'installed', steps: plan.steps };
  } catch (err) {
    return {
      ok: false,
      platform: plan.platform,
      file: plan.file,
      installed: false,
      action: 'failed',
      steps: plan.steps,
      error: err instanceof Error ? err.message : String(err),
    };
  }
}

export function uninstallService(): ServiceResult {
  const plan = servicePlan();
  if (plan.platform === 'termux') {
    // The boot script is ours to remove; the app itself is not.
    const p = bootStatus().path;
    const existed = fs.existsSync(p);
    if (existed) fs.rmSync(p, { force: true });
    return { ok: true, platform: plan.platform, file: p, installed: false, action: existed ? 'removed' : 'not installed', steps: plan.steps };
  }
  const existed = fs.existsSync(plan.file);
  if (existed) fs.rmSync(plan.file, { force: true });
  return {
    ok: true,
    platform: plan.platform,
    file: plan.file,
    installed: false,
    action: existed ? 'removed' : 'not installed',
    steps: plan.steps,
  };
}

export function serviceStatus(): ServiceResult {
  const plan = servicePlan();
  return {
    ok: true,
    platform: plan.platform,
    file: plan.file,
    installed: plan.installed,
    action: plan.installed ? 'installed' : 'not installed',
    steps: plan.steps,
  };
}
