#!/usr/bin/env node
/**
 * bench.mjs — the numbers behind the phone claims.
 *
 * "Idle under 90 MB", "install under a second", "restart is instant" are the
 * kind of sentences a README can carry for years after they stopped being true.
 * This script measures them on the machine it runs on, prints them, and (with
 * `--write`) puts them into the generated block in README.md next to the script
 * name, the date and the tolerance. The test suite then fails if the README's
 * numbers drift too far from a fresh run (test/tier2.test.ts 12.1).
 *
 *   node scripts/bench.mjs             # table, 3 samples each
 *   node scripts/bench.mjs --quick     # 1 sample (what the test runs)
 *   node scripts/bench.mjs --json      # machine-readable
 *   node scripts/bench.mjs --write     # refresh the README block
 *
 * It measures the offline mock brain on purpose: no key, no network, so the
 * numbers are about TermCrab and not about somebody's API latency.
 */
import { execFileSync, spawn } from 'node:child_process';
import fs from 'node:fs';
import net from 'node:net';
import os from 'node:os';
import path from 'node:path';

const ROOT = path.resolve(import.meta.dirname, '..');
const args = process.argv.slice(2);
const QUICK = args.includes('--quick');
const AS_JSON = args.includes('--json');
const WRITE = args.includes('--write');
const SAMPLES = QUICK ? 1 : 3;
const TOLERANCE_PCT = 40;
const BEGIN = '<!-- BEGIN BENCH (generated by scripts/bench.mjs) -->';
const END = '<!-- END BENCH -->';
const BIN = path.join(ROOT, 'dist/src/bin/termcrab.js');
const sleep = (ms) => new Promise((r) => setTimeout(r, ms));

function median(values) {
  const sorted = [...values].sort((a, b) => a - b);
  return sorted[Math.floor(sorted.length / 2)];
}

async function freePort() {
  return new Promise((resolve, reject) => {
    const srv = net.createServer();
    srv.once('error', reject);
    srv.listen(0, '127.0.0.1', () => {
      const port = srv.address().port;
      srv.close(() => resolve(port));
    });
  });
}

function connected(port, timeoutMs = 500) {
  return new Promise((resolve) => {
    const sock = net.connect({ host: '127.0.0.1', port });
    const done = (ok) => {
      sock.destroy();
      resolve(ok);
    };
    sock.setTimeout(timeoutMs, () => done(false));
    sock.once('connect', () => done(true));
    sock.once('error', () => done(false));
  });
}

/** `npm install` in a throwaway copy of package.json — the phone's slow step. */
function measureInstall() {
  const dir = fs.mkdtempSync(path.join(os.tmpdir(), 'tbench-install-'));
  try {
    const pkg = JSON.parse(fs.readFileSync(path.join(ROOT, 'package.json'), 'utf8'));
    const bare = {
      name: pkg.name,
      version: pkg.version,
      private: true,
      engines: pkg.engines,
      dependencies: pkg.dependencies,
      optionalDependencies: pkg.optionalDependencies,
    };
    fs.writeFileSync(path.join(dir, 'package.json'), `${JSON.stringify(bare, null, 2)}\n`);
    const started = performance.now();
    execFileSync('npm', ['install', '--omit=dev', '--no-optional', '--ignore-scripts', '--no-audit', '--no-fund'], {
      cwd: dir,
      stdio: 'ignore',
      env: { ...process.env, npm_config_update_notifier: 'false' },
    });
    return Math.round(performance.now() - started);
  } finally {
    fs.rmSync(dir, { recursive: true, force: true });
  }
}

function measureColdStart(home) {
  const started = performance.now();
  execFileSync(process.execPath, [BIN, 'version'], {
    env: { ...process.env, TCRAB_HOME: home },
    stdio: 'ignore',
  });
  return Math.round(performance.now() - started);
}

async function measureGateway(home, port) {
  const started = performance.now();
  const child = spawn(process.execPath, [BIN, 'gateway', '--host', '127.0.0.1', '--port', String(port)], {
    env: { ...process.env, TCRAB_HOME: home, TCRAB_LOG_LEVEL: 'error' },
    stdio: 'ignore',
    detached: false,
  });
  for (let i = 0; i < 200; i++) {
    if (await connected(port)) return { child, startMs: Math.round(performance.now() - started) };
    if (child.exitCode !== null) throw new Error(`gateway exited with ${child.exitCode}`);
    await sleep(25);
  }
  child.kill('SIGKILL');
  throw new Error('gateway never started listening');
}

function rssMb(pid) {
  const status = fs.readFileSync(`/proc/${pid}/status`, 'utf8');
  const m = /VmRSS:\s+(\d+)\s+kB/.exec(status);
  if (!m) throw new Error('VmRSS not readable');
  return Math.round(Number(m[1]) / 1024);
}

async function stopGateway(child, port) {
  const started = performance.now();
  child.kill('SIGTERM');
  await new Promise((resolve) => {
    const t = setTimeout(() => {
      child.kill('SIGKILL');
      resolve();
    }, 5000);
    child.once('exit', () => {
      clearTimeout(t);
      resolve();
    });
  });
  for (let i = 0; i < 100; i++) {
    if (!(await connected(port, 200))) break;
    await sleep(20);
  }
  return Math.round(performance.now() - started);
}

/** One real turn through the panel: message → queue → run → answer. */
async function measureTurn(port) {
  const started = performance.now();
  const res = await fetch(`http://127.0.0.1:${port}/api/chat`, {
    method: 'POST',
    headers: { 'content-type': 'application/json' },
    body: JSON.stringify({ message: 'bench: say something short', sessionId: 'bench:turn' }),
  });
  if (res.status !== 202) throw new Error(`chat returned ${res.status}`);
  const { turnId } = await res.json();
  for (let i = 0; i < 400; i++) {
    const r = await fetch(`http://127.0.0.1:${port}/api/runs/${encodeURIComponent(turnId)}`);
    if (r.status === 200) {
      const body = await r.json();
      if (['done', 'error', 'interrupted'].includes(body.status)) {
        if (body.status !== 'done') throw new Error(`bench turn ended ${body.status}`);
        return Math.round(performance.now() - started);
      }
    }
    await sleep(20);
  }
  throw new Error('bench turn never finished');
}

function renderBlock(bench) {
  const secs = (ms) => `${(ms / 1000).toFixed(2)} s`;
  return [
    BEGIN,
    '',
    `_Measured ${bench.measuredAt} on Node ${bench.node} — re-run \`node scripts/bench.mjs\` and expect the timings within ±${TOLERANCE_PCT}% (idle memory is steadier; a phone is slower, and that is what the \`docs/TERMUX.md\` guide is for)._`,
    '',
    '| what | measured | why it matters on a phone |',
    '|---|---|---|',
    `| \`npm install\` (zero runtime deps, \`--omit=dev\`) | ${secs(bench.installMs)} | the slow step that never happens |`,
    `| cold start (\`termcrab version\`) | ${bench.coldStartMs} ms | every CLI call pays it |`,
    `| idle RSS (gateway, offline brain) | ${bench.idleRssMb} MB | an old phone has ~2 GB, and the OS kills hogs |`,
    `| stop + start again (\`supervisor\`) | ${bench.restartMs} ms | a restart must be invisible |`,
    `| one real turn (message → answer, offline) | ${bench.turnMs} ms | loudness of the whole loop |`,
    '',
    END,
  ].join('\n');
}

function writeReadme(bench) {
  const file = path.join(ROOT, 'README.md');
  const doc = fs.readFileSync(file, 'utf8');
  const a = doc.indexOf(BEGIN);
  const b = doc.indexOf(END);
  const block = renderBlock(bench);
  const next = a >= 0 && b >= 0 ? doc.slice(0, a) + block + doc.slice(b + END.length) : `${doc.trimEnd()}\n\n${block}\n`;
  if (next === doc) return false;
  fs.writeFileSync(file, next, 'utf8');
  return true;
}

async function main() {
  if (!fs.existsSync(BIN)) {
    console.error(`bench: ${BIN} is missing — run: npm run build`);
    process.exit(1);
  }
  const home = fs.mkdtempSync(path.join(os.tmpdir(), 'tbench-home-'));
  const config = {
    provider: { type: 'mock', model: 'mock-1' },
    gateway: { host: '127.0.0.1', port: 0, token: '' },
  };
  fs.writeFileSync(path.join(home, 'config.json'), `${JSON.stringify(config, null, 2)}\n`);
  const port = await freePort();

  const coldStarts = [];
  for (let i = 0; i < SAMPLES; i++) coldStarts.push(measureColdStart(home));

  let child = null;
  let idleRss = 0;
  let startMs = 0;
  try {
    const boot = await measureGateway(home, port);
    child = boot.child;
    startMs = boot.startMs;
    await sleep(700); // let the schedulers settle
    idleRss = rssMb(child.pid);
    const stops = [];
    const starts = [];
    for (let i = 0; i < Math.max(1, SAMPLES - 1); i++) {
      stops.push(await stopGateway(child, port));
      const again = await measureGateway(home, port);
      child = again.child;
      starts.push(again.startMs);
      await sleep(200);
    }
    const turnMs = await measureTurn(port);
    const bench = {
      measuredAt: new Date().toISOString().slice(0, 10),
      node: process.version,
      installMs: measureInstall(),
      coldStartMs: median(coldStarts),
      idleRssMb: idleRss,
      // "stop and start again" — with a single sample we can only honestly report
      // the start half, so that is what goes in the table.
      restartMs: stops.length ? median(stops) + median(starts) : startMs,
      turnMs,
      tolerancePct: TOLERANCE_PCT,
    };
    if (WRITE) {
      const wrote = writeReadme(bench);
      if (!AS_JSON) console.log(wrote ? 'bench: README.md block refreshed' : 'bench: README.md already up to date');
    }
    if (AS_JSON) {
      console.log(JSON.stringify(bench, null, 2));
    } else if (!WRITE) {
      console.log(renderBlock(bench).split('\n').slice(1, -1).join('\n'));
    }
  } finally {
    if (child) await stopGateway(child, port);
    fs.rmSync(home, { recursive: true, force: true });
  }
}

main().catch((err) => {
  console.error(`bench failed: ${err instanceof Error ? err.message : String(err)}`);
  process.exit(1);
});
