#!/usr/bin/env node
/**
 * bench.mjs — the numbers behind the phone claims.
 *
 * "Idle under 90 MB", "install under a second", "restart is instant" are the
 * kind of sentences a README can carry for years after they stopped being true.
 * This script measures them on the machine it runs on, prints them, and (with
 * `--write`) puts them into the generated block in README.md next to the script
 * name, the date and the tolerance. The test suite then fails if the README's
 * numbers drift too far from a fresh run (test/tier2.test.ts 12.1).
 *
 *   node scripts/bench.mjs             # table, 3 samples each
 *   node scripts/bench.mjs --quick     # 1 sample (what the test runs)
 *   node scripts/bench.mjs --json      # machine-readable
 *   node scripts/bench.mjs --write     # refresh the README block
 *   node scripts/bench.mjs --budget    # exit 1 if any number is over its ceiling
 *   node scripts/bench.mjs --first-run # also compile a fresh copy (37.3)
 *
 * The ceilings in BUDGETS (37.1) are the difference between a number and a
 * promise: the README may quote whatever was measured, but the suite fails when
 * a measured number crosses the ceiling, so a regression cannot be published
 * quietly. They are deliberately loose - an alarm for "something structural
 * got slower", not a stopwatch for a busy CI.
 *
 * It measures the offline mock brain on purpose: no key, no network, so the
 * numbers are about TermCrab and not about somebody's API latency.
 */
import { execFileSync, spawn } from 'node:child_process';
import fs from 'node:fs';
import net from 'node:net';
import os from 'node:os';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

// One declaration, two callers: the ceilings live in src/core/perf.ts (38.1) and
// `termcrab perf` reads the same object, so the alarm in the suite and the alarm
// on the phone cannot disagree. dist is already required for the binary below.
const perf = await import('../dist/src/core/perf.js').catch(() => {
  console.error('bench: dist/src/core/perf.js is missing — run: npm run build');
  process.exit(1);
});

const ROOT = path.resolve(import.meta.dirname, '..');
const args = process.argv.slice(2);
const QUICK = args.includes('--quick');
const AS_JSON = args.includes('--json');
const WRITE = args.includes('--write');
const SAMPLES = QUICK ? 1 : 3;
const TOLERANCE_PCT = 40;
const BUDGET = args.includes('--budget');
// The first-run build copies the checkout into a temp dir and compiles it, so it
// is opt-in: tier3i asks for it, the quick README check does not pay for it.
const FIRST_RUN = args.includes('--first-run') || WRITE || !AS_JSON;
const BEGIN = '<!-- BEGIN BENCH (generated by scripts/bench.mjs) -->';
const END = '<!-- END BENCH -->';
const BIN = path.join(ROOT, 'dist/src/bin/termcrab.js');
const sleep = (ms) => new Promise((r) => setTimeout(r, ms));

/**
 * The absolute ceilings (37.1). Measured 2026-10-04 on the dev box while these
 * were written: cold start 133 ms, idle RSS 71 MB, restart 136 ms, one turn
 * 88 ms, install 231 ms. Each ceiling is a multiple of that (where the metric
 * can spike on a shared machine) so the alarm fires on a *regression*, not on
 * jitter - see docs/PERFORMANCE.md for what to do when one trips.
 */
/** The ceilings, straight from src/core/perf.ts (the single declaration). */
export const BUDGETS = Object.fromEntries(
  Object.entries(perf.PERF_CEILINGS).map(([key, c]) => [key, { max: c.max, why: c.why }]),
);

/** Which ceilings a measured run misses. Exported so the suite can test it. */
export function checkBudgets(bench) {
  return Object.entries(BUDGETS).map(([key, { max, why }]) => ({
    key,
    value: bench[key],
    max,
    ok: typeof bench[key] === 'number' && bench[key] <= max,
    why,
  }));
}

function median(values) {
  const sorted = [...values].sort((a, b) => a - b);
  return sorted[Math.floor(sorted.length / 2)];
}

async function freePort() {
  return new Promise((resolve, reject) => {
    const srv = net.createServer();
    srv.once('error', reject);
    srv.listen(0, '127.0.0.1', () => {
      const port = srv.address().port;
      srv.close(() => resolve(port));
    });
  });
}

function connected(port, timeoutMs = 500) {
  return new Promise((resolve) => {
    const sock = net.connect({ host: '127.0.0.1', port });
    const done = (ok) => {
      sock.destroy();
      resolve(ok);
    };
    sock.setTimeout(timeoutMs, () => done(false));
    sock.once('connect', () => done(true));
    sock.once('error', () => done(false));
  });
}

/** `npm install` in a throwaway copy of package.json — the phone's slow step. */
function measureInstall() {
  const dir = fs.mkdtempSync(path.join(os.tmpdir(), 'tbench-install-'));
  try {
    const pkg = JSON.parse(fs.readFileSync(path.join(ROOT, 'package.json'), 'utf8'));
    const bare = {
      name: pkg.name,
      version: pkg.version,
      private: true,
      engines: pkg.engines,
      dependencies: pkg.dependencies,
      optionalDependencies: pkg.optionalDependencies,
    };
    fs.writeFileSync(path.join(dir, 'package.json'), `${JSON.stringify(bare, null, 2)}\n`);
    const started = performance.now();
    execFileSync('npm', ['install', '--omit=dev', '--no-optional', '--ignore-scripts', '--no-audit', '--no-fund'], {
      cwd: dir,
      stdio: 'ignore',
      env: { ...process.env, npm_config_update_notifier: 'false' },
    });
    return Math.round(performance.now() - started);
  } finally {
    fs.rmSync(dir, { recursive: true, force: true });
  }
}

function measureColdStart(home) {
  const started = performance.now();
  execFileSync(process.execPath, [BIN, 'version'], {
    env: { ...process.env, TCRAB_HOME: home },
    stdio: 'ignore',
  });
  return Math.round(performance.now() - started);
}

async function measureGateway(home, port) {
  const started = performance.now();
  const child = spawn(process.execPath, [BIN, 'gateway', '--host', '127.0.0.1', '--port', String(port)], {
    env: { ...process.env, TCRAB_HOME: home, TCRAB_LOG_LEVEL: 'error' },
    stdio: 'ignore',
    detached: false,
  });
  for (let i = 0; i < 200; i++) {
    if (await connected(port)) return { child, startMs: Math.round(performance.now() - started) };
    if (child.exitCode !== null) throw new Error(`gateway exited with ${child.exitCode}`);
    await sleep(25);
  }
  child.kill('SIGKILL');
  throw new Error('gateway never started listening');
}

function rssMb(pid) {
  const status = fs.readFileSync(`/proc/${pid}/status`, 'utf8');
  const m = /VmRSS:\s+(\d+)\s+kB/.exec(status);
  if (!m) throw new Error('VmRSS not readable');
  return Math.round(Number(m[1]) / 1024);
}

async function stopGateway(child, port) {
  const started = performance.now();
  child.kill('SIGTERM');
  await new Promise((resolve) => {
    const t = setTimeout(() => {
      child.kill('SIGKILL');
      resolve();
    }, 5000);
    child.once('exit', () => {
      clearTimeout(t);
      resolve();
    });
  });
  for (let i = 0; i < 100; i++) {
    if (!(await connected(port, 200))) break;
    await sleep(20);
  }
  return Math.round(performance.now() - started);
}

/**
 * 37.3 — what the very first `./termcrab` costs on a fresh checkout: it copies
 * the tree without dist/, symlinks the installed dev packages, runs the
 * launcher (npm install is skipped: node_modules is there), and then touches a
 * source to measure the incremental rebuild the "git pull" path pays.
 */
function measureFirstRun() {
  const dir = fs.mkdtempSync(path.join(os.tmpdir(), 'tbench-first-'));
  const home = fs.mkdtempSync(path.join(os.tmpdir(), 'tbench-first-home-'));
  try {
    for (const item of ['src', 'ui', 'test/fixtures', 'scripts/copy-assets.mjs', 'package.json', 'tsconfig.json', 'termcrab']) {
      fs.cpSync(path.join(ROOT, item), path.join(dir, item), { recursive: true });
    }
    fs.chmodSync(path.join(dir, 'termcrab'), 0o755);
    fs.symlinkSync(path.join(ROOT, 'node_modules'), path.join(dir, 'node_modules'), 'dir');
    const env = { ...process.env, TCRAB_HOME: home, NO_COLOR: '1' };
    const started = performance.now();
    execFileSync(path.join(dir, 'termcrab'), ['version'], { cwd: dir, env, stdio: 'ignore' });
    const firstRunMs = Math.round(performance.now() - started);
    const now = new Date();
    fs.utimesSync(path.join(dir, 'src', 'cli.ts'), now, now);
    const rebuildStarted = performance.now();
    execFileSync(path.join(dir, 'termcrab'), ['version'], { cwd: dir, env, stdio: 'ignore' });
    const rebuildMs = Math.round(performance.now() - rebuildStarted);
    return { firstRunMs, rebuildMs };
  } finally {
    fs.rmSync(dir, { recursive: true, force: true });
    fs.rmSync(home, { recursive: true, force: true });
  }
}

/** One real turn through the panel: message → queue → run → answer. */
async function measureTurn(port) {
  const started = performance.now();
  const res = await fetch(`http://127.0.0.1:${port}/api/chat`, {
    method: 'POST',
    headers: { 'content-type': 'application/json' },
    body: JSON.stringify({ message: 'bench: say something short', sessionId: 'bench:turn' }),
  });
  if (res.status !== 202) throw new Error(`chat returned ${res.status}`);
  const { turnId } = await res.json();
  for (let i = 0; i < 400; i++) {
    const r = await fetch(`http://127.0.0.1:${port}/api/runs/${encodeURIComponent(turnId)}`);
    if (r.status === 200) {
      const body = await r.json();
      if (['done', 'error', 'interrupted'].includes(body.status)) {
        if (body.status !== 'done') throw new Error(`bench turn ended ${body.status}`);
        return Math.round(performance.now() - started);
      }
    }
    await sleep(20);
  }
  throw new Error('bench turn never finished');
}

function renderBlock(bench) {
  const secs = (ms) => `${(ms / 1000).toFixed(2)} s`;
  return [
    BEGIN,
    '',
    `_Measured ${bench.measuredAt} on Node ${bench.node} — re-run \`node scripts/bench.mjs\` and expect the timings within ±${TOLERANCE_PCT}% (idle memory is steadier; a phone is slower, and that is what the \`docs/TERMUX.md\` guide is for)._`,
    '',
    '| what | measured | budget (the alarm) | why it matters on a phone |',
    '|---|---|---|---|',
    `| \`npm install\` (zero runtime deps, \`--omit=dev\`) | ${bench.installMs} ms | ${BUDGETS.installMs.max} ms | the slow step that never happens |`,
    `| cold start (\`termcrab version\`) | ${bench.coldStartMs} ms | ${BUDGETS.coldStartMs.max} ms | every CLI call pays it |`,
    `| idle RSS (gateway, offline brain) | ${bench.idleRssMb} MB | ${BUDGETS.idleRssMb.max} MB | an old phone has ~2 GB, and the OS kills hogs |`,
    `| stop + start again (\`supervisor\`) | ${bench.restartMs} ms | ${BUDGETS.restartMs.max} ms | a restart must be invisible |`,
    `| one real turn (message → answer, offline) | ${bench.turnMs} ms | ${BUDGETS.turnMs.max} ms | loudness of the whole loop |`,
    `| first run from a fresh checkout (\`./termcrab\`, compiles) | ${bench.firstRunMs} ms | ${BUDGETS.firstRunMs.max} ms | the one wait a new user pays, once |`,
    `| rebuild after a \`git pull\` (incremental) | ${bench.rebuildMs} ms | ${BUDGETS.rebuildMs.max} ms | how long "pull, then run" keeps you |`,
    '',
    END,
  ].join('\n');
}

function writeReadme(bench) {
  const file = path.join(ROOT, 'README.md');
  const doc = fs.readFileSync(file, 'utf8');
  const a = doc.indexOf(BEGIN);
  const b = doc.indexOf(END);
  const block = renderBlock(bench);
  const next = a >= 0 && b >= 0 ? doc.slice(0, a) + block + doc.slice(b + END.length) : `${doc.trimEnd()}\n\n${block}\n`;
  if (next === doc) return false;
  fs.writeFileSync(file, next, 'utf8');
  return true;
}

async function main() {
  if (!fs.existsSync(BIN)) {
    console.error(`bench: ${BIN} is missing — run: npm run build`);
    process.exit(1);
  }
  const home = fs.mkdtempSync(path.join(os.tmpdir(), 'tbench-home-'));
  const config = {
    provider: { type: 'mock', model: 'mock-1' },
    gateway: { host: '127.0.0.1', port: 0, token: '' },
  };
  fs.writeFileSync(path.join(home, 'config.json'), `${JSON.stringify(config, null, 2)}\n`);
  const port = await freePort();

  const coldStarts = [];
  for (let i = 0; i < SAMPLES; i++) coldStarts.push(measureColdStart(home));

  let child = null;
  let idleRss = 0;
  let startMs = 0;
  try {
    const boot = await measureGateway(home, port);
    child = boot.child;
    startMs = boot.startMs;
    await sleep(700); // let the schedulers settle
    idleRss = rssMb(child.pid);
    const stops = [];
    const starts = [];
    for (let i = 0; i < Math.max(1, SAMPLES - 1); i++) {
      stops.push(await stopGateway(child, port));
      const again = await measureGateway(home, port);
      child = again.child;
      starts.push(again.startMs);
      await sleep(200);
    }
    const turnMs = await measureTurn(port);
    const bench = {
      measuredAt: new Date().toISOString().slice(0, 10),
      node: process.version,
      installMs: measureInstall(),
      coldStartMs: median(coldStarts),
      idleRssMb: idleRss,
      // "stop and start again" — with a single sample we can only honestly report
      // the start half, so that is what goes in the table.
      restartMs: stops.length ? median(stops) + median(starts) : startMs,
      turnMs,
      ...(FIRST_RUN ? measureFirstRun() : {}),
      tolerancePct: TOLERANCE_PCT,
      budget: checkBudgets({
        installMs: 0,
        coldStartMs: 0,
        idleRssMb: 0,
        restartMs: 0,
        turnMs: 0,
      }).map((b) => ({ key: b.key, max: b.max, why: b.why })),
    };
    const budget = checkBudgets(bench).filter((b) => typeof b.value === 'number');
    bench.overBudget = budget.filter((b) => !b.ok).map((b) => b.key);
    if (WRITE) {
      const wrote = writeReadme(bench);
      if (!AS_JSON) console.log(wrote ? 'bench: README.md block refreshed' : 'bench: README.md already up to date');
    }
    if (AS_JSON) {
      console.log(JSON.stringify(bench, null, 2));
    } else if (!WRITE) {
      console.log(renderBlock(bench).split('\n').slice(1, -1).join('\n'));
    }
    if (BUDGET) {
      // --json keeps stdout parseable: the per-metric lines go to stderr there.
      const sink = AS_JSON ? console.error : console.log;
      for (const b of budget) {
        sink(`bench: ${b.ok ? 'ok  ' : 'OVER'} ${b.key} ${b.value} / ${b.max}${b.ok ? '' : ` - ${b.why}`}`);
      }
      if (bench.overBudget.length) {
        console.error(`bench: over budget: ${bench.overBudget.join(', ')} - see docs/PERFORMANCE.md`);
        process.exitCode = 1;
      } else if (!AS_JSON) {
        console.log(`bench: within budget (${budget.length}/${budget.length})`);
      }
    }
  } finally {
    if (child) await stopGateway(child, port);
    fs.rmSync(home, { recursive: true, force: true });
  }
}

// Importable: test/tier3i.test.ts pulls in checkBudgets to test the alarm itself
// (a fabricated over-budget number must be reported as over). Only run the
// measurements when this file *is* the program.
if (process.argv[1] && path.resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  main().catch((err) => {
    console.error(`bench failed: ${err instanceof Error ? err.message : String(err)}`);
    process.exit(1);
  });
}
