#!/usr/bin/env node
/**
 * bench.mjs — the numbers behind the phone claims.
 *
 * "Idle under 90 MB", "install under a second", "restart is instant" are the
 * kind of sentences a README can carry for years after they stopped being true.
 * This script measures them on the machine it runs on, prints them, and (with
 * `--write`) puts them into the generated block in README.md next to the script
 * name, the date and the tolerance. The test suite then fails if the README's
 * numbers drift too far from a fresh run (test/tier2.test.ts 12.1).
 *
 *   node scripts/bench.mjs             # table, 3 samples each
 *   node scripts/bench.mjs --quick     # 1 sample (what the test runs)
 *   node scripts/bench.mjs --json      # machine-readable
 *   node scripts/bench.mjs --write     # refresh the README block
 *   node scripts/bench.mjs --budget    # exit 1 if any number is over its ceiling
 *   node scripts/bench.mjs --first-run # also compile a fresh copy (37.3)
 *
 * The ceilings in BUDGETS (37.1) are the difference between a number and a
 * promise: the README may quote whatever was measured, but the suite fails when
 * a measured number crosses the ceiling, so a regression cannot be published
 * quietly. They are deliberately loose - an alarm for "something structural
 * got slower", not a stopwatch for a busy CI.
 *
 * It measures the offline mock brain on purpose: no key, no network, so the
 * numbers are about TermCrab and not about somebody's API latency.
 */
import { execFileSync, spawn } from 'node:child_process';
import fs from 'node:fs';
import net from 'node:net';
import os from 'node:os';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

// One declaration, two callers: the ceilings live in src/core/perf.ts (38.1) and
// `termcrab perf` reads the same object, so the alarm in the suite and the alarm
// on the phone cannot disagree. dist is already required for the binary below.
const perf = await import('../dist/src/core/perf.js').catch(() => {
  console.error('bench: dist/src/core/perf.js is missing — run: npm run build');
  process.exit(1);
});

const ROOT = path.resolve(import.meta.dirname, '..');
const args = process.argv.slice(2);
const QUICK = args.includes('--quick');
const AS_JSON = args.includes('--json');
const WRITE = args.includes('--write');
const SAMPLES = QUICK ? 1 : 3;
const TOLERANCE_PCT = 40;
const BUDGET = args.includes('--budget');
// The first-run build copies the checkout into a temp dir and compiles it, so it
// is opt-in: tier3i asks for it, the quick README check does not pay for it.
const FIRST_RUN = args.includes('--first-run') || WRITE || !AS_JSON;
const BEGIN = '<!-- BEGIN BENCH (generated by scripts/bench.mjs) -->';
const END = '<!-- END BENCH -->';
const BIN = path.join(ROOT, 'dist/src/bin/termcrab.js');
const sleep = (ms) => new Promise((r) => setTimeout(r, ms));

/**
 * The absolute ceilings (37.1). Measured 2026-10-04 on the dev box while these
 * were written: cold start 133 ms, idle RSS 71 MB, restart 136 ms, one turn
 * 88 ms, install 231 ms. Each ceiling is a multiple of that (where the metric
 * can spike on a shared machine) so the alarm fires on a *regression*, not on
 * jitter - see docs/PERFORMANCE.md for what to do when one trips.
 */
/** The ceilings, straight from src/core/perf.ts (the single declaration). */
export const BUDGETS = Object.fromEntries(
  Object.entries(perf.PERF_CEILINGS).map(([key, c]) => [key, { max: c.max, why: c.why }]),
);

/** Which ceilings a measured run misses. Exported so the suite can test it. */
export function checkBudgets(bench) {
  return Object.entries(BUDGETS).map(([key, { max, why }]) => ({
    key,
    value: bench[key],
    max,
    ok: typeof bench[key] === 'number' && bench[key] <= max,
    why,
  }));
}

function median(values) {
  const sorted = [...values].sort((a, b) => a - b);
  return sorted[Math.floor(sorted.length / 2)];
}

async function freePort() {
  return new Promise((resolve, reject) => {
    const srv = net.createServer();
    srv.once('error', reject);
    srv.listen(0, '127.0.0.1', () => {
      const port = srv.address().port;
      srv.close(() => resolve(port));
    });
  });
}

function connected(port, timeoutMs = 500) {
  return new Promise((resolve) => {
    const sock = net.connect({ host: '127.0.0.1', port });
    const done = (ok) => {
      sock.destroy();
      resolve(ok);
    };
    sock.setTimeout(timeoutMs, () => done(false));
    sock.once('connect', () => done(true));
    sock.once('error', () => done(false));
  });
}

/** `npm install` in a throwaway copy of package.json — the phone's slow step. */
function measureInstall() {
  const dir = fs.mkdtempSync(path.join(os.tmpdir(), 'tbench-install-'));
  try {
    const pkg = JSON.parse(fs.readFileSync(path.join(ROOT, 'package.json'), 'utf8'));
    const bare = {
      name: pkg.name,
      version: pkg.version,
      private: true,
      engines: pkg.engines,
      dependencies: pkg.dependencies,
      optionalDependencies: pkg.optionalDependencies,
    };
    fs.writeFileSync(path.join(dir, 'package.json'), `${JSON.stringify(bare, null, 2)}\n`);
    const started = performance.now();
    execFileSync('npm', ['install', '--omit=dev', '--no-optional', '--ignore-scripts', '--no-audit', '--no-fund'], {
      cwd: dir,
      stdio: 'ignore',
      env: { ...process.env, npm_config_update_notifier: 'false' },
    });
    return Math.round(performance.now() - started);
  } finally {
    fs.rmSync(dir, { recursive: true, force: true });
  }
}

function measureColdStart(home) {
  const started = performance.now();
  execFileSync(process.execPath, [BIN, 'version'], {
    env: { ...process.env, TCRAB_HOME: home },
    stdio: 'ignore',
  });
  return Math.round(performance.now() - started);
}

async function measureGateway(home, port) {
  const started = performance.now();
  const child = spawn(process.execPath, [BIN, 'gateway', '--host', '127.0.0.1', '--port', String(port)], {
    env: { ...process.env, TCRAB_HOME: home, TCRAB_LOG_LEVEL: 'error' },
    stdio: 'ignore',
    detached: false,
  });
  for (let i = 0; i < 200; i++) {
    if (await connected(port)) return { child, startMs: Math.round(performance.now() - started) };
    if (child.exitCode !== null) throw new Error(`gateway exited with ${child.exitCode}`);
    await sleep(25);
  }
  child.kill('SIGKILL');
  throw new Error('gateway never started listening');
}

function rssMb(pid) {
  const status = fs.readFileSync(`/proc/${pid}/status`, 'utf8');
  const m = /VmRSS:\s+(\d+)\s+kB/.exec(status);
  if (!m) throw new Error('VmRSS not readable');
  return Math.round(Number(m[1]) / 1024);
}

async function stopGateway(child, port) {
  const started = performance.now();
  child.kill('SIGTERM');
  await new Promise((resolve) => {
    const t = setTimeout(() => {
      child.kill('SIGKILL');
      resolve();
    }, 5000);
    child.once('exit', () => {
      clearTimeout(t);
      resolve();
    });
  });
  for (let i = 0; i < 100; i++) {
    if (!(await connected(port, 200))) break;
    await sleep(20);
  }
  return Math.round(performance.now() - started);
}

/**
 * 37.3 — what the very first `./termcrab` costs on a fresh checkout: it copies
 * the tree without dist/, symlinks the installed dev packages, runs the
 * launcher (npm install is skipped: node_modules is there), and then touches a
 * source to measure the incremental rebuild the "git pull" path pays.
 */
function measureFirstRun() {
  const dir = fs.mkdtempSync(path.join(os.tmpdir(), 'tbench-first-'));
  const home = fs.mkdtempSync(path.join(os.tmpdir(), 'tbench-first-home-'));
  try {
    for (const item of ['src', 'ui', 'test/fixtures', 'scripts/copy-assets.mjs', 'package.json', 'tsconfig.json', 'termcrab']) {
      fs.cpSync(path.join(ROOT, item), path.join(dir, item), { recursive: true });
    }
    fs.chmodSync(path.join(dir, 'termcrab'), 0o755);
    fs.symlinkSync(path.join(ROOT, 'node_modules'), path.join(dir, 'node_modules'), 'dir');
    const env = { ...process.env, TCRAB_HOME: home, NO_COLOR: '1' };
    const started = performance.now();
    execFileSync(path.join(dir, 'termcrab'), ['version'], { cwd: dir, env, stdio: 'ignore' });
    const firstRunMs = Math.round(performance.now() - started);
    const now = new Date();
    fs.utimesSync(path.join(dir, 'src', 'cli.ts'), now, now);
    const rebuildStarted = performance.now();
    execFileSync(path.join(dir, 'termcrab'), ['version'], { cwd: dir, env, stdio: 'ignore' });
    const rebuildMs = Math.round(performance.now() - rebuildStarted);
    return { firstRunMs, rebuildMs };
  } finally {
    fs.rmSync(dir, { recursive: true, force: true });
    fs.rmSync(home, { recursive: true, force: true });
  }
}

/**
 * 39.2 — one memory search over a real index.
 *
 * The index is plain JSONL scanned in memory: filter to the rows this model can
 * compare, cosine each, sort, take k. That is O(n) on purpose (a phone has no
 * vector database and does not need one), and this measurement is what keeps it
 * that way — the ceiling would catch a search that quietly became quadratic, or
 * an index that started loading from disk on every query.
 *
 * The embedder is a deterministic local pseudo-embedder so the number is about
 * *our* scan and not about somebody's API latency. 10 000 rows is roughly a year
 * of memory on a phone.
 */
export const SEARCH_ROWS = 10_000;

/**
 * 39.3 — the offline docs page, built for real.
 *
 * The page is 60 documents rendered into one HTML file by the panel's own
 * markdown renderer, and the gateway serves it on demand. Two numbers matter on
 * a phone: how long a rebuild takes (the panel's rebuild button, `termcrab docs
 * rebuild`) and how big the file is (a phone tab with 3 MB of inline markdown is
 * fine; 40 MB is not). Both get ceilings.
 */
/**
 * 39.4 — the loops a person feels: a chatty group, a queue that was owed, and
 * the poll plumbing itself. All three write into a throwaway TCRAB_HOME, and
 * the bot calls go to a local stub, so the numbers are about our code.
 */
async function measureLoops() {
  const home = fs.mkdtempSync(path.join(os.tmpdir(), 'tbench-loops-'));
  const prevHome = process.env.TCRAB_HOME;
  process.env.TCRAB_HOME = home;
  const http = await import('node:http');
  // A stub Bot API: getUpdates answers 50 updates, anything else a tiny object.
  let calls = 0;
  const server = http.createServer((req, res) => {
    let raw = '';
    req.on('data', (c) => (raw += c));
    req.on('end', () => {
      calls += 1;
      const url = new URL(req.url ?? '/', 'http://127.0.0.1');
      const body = raw ? JSON.parse(raw) : {};
      const method = url.pathname.split('/').pop();
      let result = {};
      if (method === 'getUpdates') {
        const offset = Number(body.offset ?? 0);
        result = Array.from({ length: 50 }, (_, i) => ({
          update_id: offset + i,
          message: {
            message_id: i,
            chat: { id: 42, type: 'group' },
            from: { id: 7, username: 'someone' },
            text: `group chatter ${offset + i}`,
          },
        }));
      }
      res.writeHead(200, { 'content-type': 'application/json' });
      res.end(JSON.stringify({ ok: true, result }));
    });
  });
  await new Promise((r) => server.listen(0, '127.0.0.1', r));
  const port = server.address().port;
  try {
    const { recordRoomMessage } = await import(path.join(ROOT, 'dist', 'src', 'channels', 'rooms.js'));
    const { outboxPush, outboxPending, outboxMarkSending, outboxAck, outboxSweep } = await import(
      path.join(ROOT, 'dist', 'src', 'mobile', 'outbox.js')
    );
    const { TelegramApi } = await import(path.join(ROOT, 'dist', 'src', 'channels', 'api.js'));

    // A chatty group: 200 messages into one room, which is at its cap the whole
    // time — every append pays the trim it exists to pay.
    const roomStarted = performance.now();
    for (let i = 0; i < 200; i++) {
      recordRoomMessage({
        channel: 'telegram',
        room: 'group-42',
        from: `user${i % 5}`,
        text: `message number ${i} about the usual things`,
        addressed: false,
      });
    }
    const roomWriteMs = Math.round(performance.now() - roomStarted);

    // A queue that was owed: 200 messages queued, claimed, acked and swept.
    const outboxStarted = performance.now();
    const ids = [];
    for (let i = 0; i < 200; i++) ids.push(outboxPush({ channel: 'telegram', chatId: 42, text: `owed reply ${i}` }).id);
    for (const item of outboxPending('telegram', { staleMs: 0 })) {
      outboxMarkSending(item.id);
      outboxAck(item.id);
    }
    outboxSweep(0);
    const outboxDrainMs = Math.round(performance.now() - outboxStarted);

    // The poll plumbing: 50 cycles of 50 updates through the real client.
    const api = new TelegramApi('123:ABC', `http://127.0.0.1:${port}`);
    const pollStarted = performance.now();
    let offset = 0;
    for (let cycle = 0; cycle < 50; cycle++) {
      const updates = await api.getUpdates(offset, 0);
      for (const upd of updates) offset = upd.update_id + 1;
    }
    const telegramPollMs = Math.round(performance.now() - pollStarted);
    if (calls < 50) throw new Error(`the stub only saw ${calls} call(s)`);

    return { roomWriteMs, outboxDrainMs, telegramPollMs };
  } finally {
    server.close();
    fs.rmSync(home, { recursive: true, force: true });
    if (prevHome === undefined) delete process.env.TCRAB_HOME;
    else process.env.TCRAB_HOME = prevHome;
  }
}

async function measureDocs(samples) {
  const { buildDocsSite } = await import(path.join(ROOT, 'dist', 'src', 'docs', 'site.js'));
  let bestMs = Number.POSITIVE_INFINITY;
  let bytes = 0;
  let docs = 0;
  for (let i = 0; i < samples; i++) {
    const started = performance.now();
    const built = buildDocsSite({});
    bestMs = Math.min(bestMs, performance.now() - started);
    bytes = built.bytes;
    docs = built.docs.length;
  }
  if (docs < 10) throw new Error(`the docs build only saw ${docs} document(s)`);
  return { docsMs: Math.round(bestMs * 10) / 10, docsKb: Math.round(bytes / 1024) };
}

function pseudoVector(text, dim = 384) {
  const v = new Array(dim);
  let h = 2166136261;
  for (let i = 0; i < text.length; i++) {
    h ^= text.charCodeAt(i);
    h = Math.imul(h, 16777619);
  }
  for (let i = 0; i < dim; i++) {
    h ^= h << 13;
    h ^= h >>> 17;
    h ^= h << 5;
    v[i] = ((h >>> 0) / 4294967296) * 2 - 1;
  }
  return v;
}

async function measureSearch(samples) {
  const dir = fs.mkdtempSync(path.join(os.tmpdir(), 'tbench-search-'));
  try {
    const { EmbeddingIndex } = await import(path.join(ROOT, 'dist', 'src', 'agent', 'embed.js'));
    const embedder = { embed: async (texts) => texts.map((t) => pseudoVector(t)), name: () => 'bench:deterministic' };
    const file = path.join(dir, 'index.jsonl');
    const lines = [];
    for (let i = 0; i < SEARCH_ROWS; i++) {
      const text = `memory row ${i} about ${i % 7 === 0 ? 'battery and charging habits' : i % 5 === 0 ? 'the docs site and releases' : 'ordinary notes'}`;
      lines.push(JSON.stringify({ id: `m${i}`, text, vec: pseudoVector(text), provider: 'bench', model: 'deterministic' }));
    }
    fs.writeFileSync(file, `${lines.join('\n')}\n`);
    const index = new EmbeddingIndex(file, embedder);
    const times = [];
    for (let i = 0; i < samples; i++) {
      const started = performance.now();
      const hits = await index.search(`what did I say about row ${i}`, 5);
      times.push(performance.now() - started);
      if (i === 0 && hits.length === 0) throw new Error('the search returned nothing over its own index');
    }
    return Math.round(median(times) * 10) / 10;
  } finally {
    fs.rmSync(dir, { recursive: true, force: true });
  }
}

/**
 * 39.5 — the cold checkout, from nothing: what a new person actually pays.
 *
 * `measureFirstRun` symlinks this repo's `node_modules` (the developer's second
 * run); this one does the real thing — a copy of the tree, no `dist/`, no
 * `node_modules`, an **isolated npm cache** so it cannot freeload on whatever
 * npm already downloaded here, then `npm install` and `./termcrab version`
 * (which compiles). Two numbers: the install, and the whole first contact.
 */
function measureColdCheckout() {
  const dir = fs.mkdtempSync(path.join(os.tmpdir(), 'tbench-cold-'));
  const home = fs.mkdtempSync(path.join(os.tmpdir(), 'tbench-cold-home-'));
  const cache = fs.mkdtempSync(path.join(os.tmpdir(), 'tbench-cold-cache-'));
  try {
    for (const item of ['src', 'ui', 'test/fixtures', 'scripts', 'package.json', 'package-lock.json', 'tsconfig.json', 'tsconfig.test.json', 'termcrab']) {
      fs.cpSync(path.join(ROOT, item), path.join(dir, item), { recursive: true });
    }
    fs.chmodSync(path.join(dir, 'termcrab'), 0o755);
    const env = { ...process.env, TCRAB_HOME: home, NO_COLOR: '1', npm_config_cache: cache, npm_config_update_notifier: 'false' };
    const installStarted = performance.now();
    execFileSync('npm', ['install', '--no-fund', '--no-audit'], { cwd: dir, env, stdio: 'ignore' });
    const coldInstallMs = Math.round(performance.now() - installStarted);
    const commandStarted = performance.now();
    execFileSync(path.join(dir, 'termcrab'), ['version'], { cwd: dir, env, stdio: 'ignore' });
    const coldCheckoutMs = Math.round(performance.now() - installStarted);
    const commandMs = Math.round(performance.now() - commandStarted);
    return { coldInstallMs, coldCheckoutMs, coldCommandMs: commandMs };
  } finally {
    fs.rmSync(dir, { recursive: true, force: true });
    fs.rmSync(home, { recursive: true, force: true });
    fs.rmSync(cache, { recursive: true, force: true });
  }
}

/** One real turn through the panel: message → queue → run → answer. */
async function measureTurn(port) {
  const started = performance.now();
  const res = await fetch(`http://127.0.0.1:${port}/api/chat`, {
    method: 'POST',
    headers: { 'content-type': 'application/json' },
    body: JSON.stringify({ message: 'bench: say something short', sessionId: 'bench:turn' }),
  });
  if (res.status !== 202) throw new Error(`chat returned ${res.status}`);
  const { turnId } = await res.json();
  for (let i = 0; i < 400; i++) {
    const r = await fetch(`http://127.0.0.1:${port}/api/runs/${encodeURIComponent(turnId)}`);
    if (r.status === 200) {
      const body = await r.json();
      if (['done', 'error', 'interrupted'].includes(body.status)) {
        if (body.status !== 'done') throw new Error(`bench turn ended ${body.status}`);
        return Math.round(performance.now() - started);
      }
    }
    await sleep(20);
  }
  throw new Error('bench turn never finished');
}

function renderBlock(bench) {
  const secs = (ms) => `${(ms / 1000).toFixed(2)} s`;
  return [
    BEGIN,
    '',
    `_Measured ${bench.measuredAt} on Node ${bench.node} — re-run \`node scripts/bench.mjs\` and expect the timings within ±${TOLERANCE_PCT}% (idle memory is steadier; a phone is slower, and that is what the \`docs/TERMUX.md\` guide is for)._`,
    '',
    '| what | measured | budget (the alarm) | why it matters on a phone |',
    '|---|---|---|---|',
    `| \`npm install\` (zero runtime deps, \`--omit=dev\`) | ${bench.installMs} ms | ${BUDGETS.installMs.max} ms | the slow step that never happens |`,
    `| cold start (\`termcrab version\`) | ${bench.coldStartMs} ms | ${BUDGETS.coldStartMs.max} ms | every CLI call pays it |`,
    `| idle RSS (gateway, offline brain) | ${bench.idleRssMb} MB | ${BUDGETS.idleRssMb.max} MB | an old phone has ~2 GB, and the OS kills hogs |`,
    `| stop + start again (\`supervisor\`) | ${bench.restartMs} ms | ${BUDGETS.restartMs.max} ms | a restart must be invisible |`,
    `| one real turn (message → answer, offline) | ${bench.turnMs} ms | ${BUDGETS.turnMs.max} ms | loudness of the whole loop |`,
    `| one memory search over ${SEARCH_ROWS.toLocaleString('en-US')} vectors | ${bench.searchMs} ms | ${BUDGETS.searchMs.max} ms | a chatty month of memory must stay instant |`,
    `| the offline docs page, built (60 docs) | ${bench.docsMs} ms | ${BUDGETS.docsMs.max} ms | the panel's rebuild button must stay a blink |`,
    `| the built docs page on disk | ${bench.docsKb} KB | ${BUDGETS.docsKb.max} KB | one HTML file a phone has to hold |`,
    `| a chatty group: 200 messages into one room | ${bench.roomWriteMs} ms | ${BUDGETS.roomWriteMs.max} ms | every message pays the trim that keeps the room bounded |`,
    `| a queue that was owed: 200 messages queued, acked, swept | ${bench.outboxDrainMs} ms | ${BUDGETS.outboxDrainMs.max} ms | a phone that was offline has to flush without a stall |`,
    `| 50 poll cycles of 50 updates (local stub) | ${bench.telegramPollMs} ms | ${BUDGETS.telegramPollMs.max} ms | the plumbing between Telegram and our handlers |`,
    `| first run from a fresh checkout (\`./termcrab\`, compiles) | ${bench.firstRunMs} ms | ${BUDGETS.firstRunMs.max} ms | the one wait a new user pays, once |`,
    `| rebuild after a \`git pull\` (incremental) | ${bench.rebuildMs} ms | ${BUDGETS.rebuildMs.max} ms | how long "pull, then run" keeps you |`,
    `| a cold checkout: \`npm install\` (empty npm cache) | ${bench.coldInstallMs} ms | ${BUDGETS.coldInstallMs.max} ms | three dev packages, zero runtime ones — on mobile data this is the whole download |`,
    `| a cold checkout, end to end (install → \`./termcrab\` answers) | ${bench.coldCheckoutMs} ms | ${BUDGETS.coldCheckoutMs.max} ms | the complete first contact, measured from nothing |`,
    '',
    END,
  ].join('\n');
}

function writeReadme(bench) {
  const file = path.join(ROOT, 'README.md');
  const doc = fs.readFileSync(file, 'utf8');
  const a = doc.indexOf(BEGIN);
  const b = doc.indexOf(END);
  const block = renderBlock(bench);
  const next = a >= 0 && b >= 0 ? doc.slice(0, a) + block + doc.slice(b + END.length) : `${doc.trimEnd()}\n\n${block}\n`;
  if (next === doc) return false;
  fs.writeFileSync(file, next, 'utf8');
  return true;
}

async function main() {
  if (!fs.existsSync(BIN)) {
    console.error(`bench: ${BIN} is missing — run: npm run build`);
    process.exit(1);
  }
  const home = fs.mkdtempSync(path.join(os.tmpdir(), 'tbench-home-'));
  const config = {
    provider: { type: 'mock', model: 'mock-1' },
    gateway: { host: '127.0.0.1', port: 0, token: '' },
  };
  fs.writeFileSync(path.join(home, 'config.json'), `${JSON.stringify(config, null, 2)}\n`);
  const port = await freePort();

  const coldStarts = [];
  for (let i = 0; i < SAMPLES; i++) coldStarts.push(measureColdStart(home));

  let child = null;
  let idleRss = 0;
  let startMs = 0;
  try {
    const boot = await measureGateway(home, port);
    child = boot.child;
    startMs = boot.startMs;
    await sleep(700); // let the schedulers settle
    idleRss = rssMb(child.pid);
    const stops = [];
    const starts = [];
    for (let i = 0; i < Math.max(1, SAMPLES - 1); i++) {
      stops.push(await stopGateway(child, port));
      const again = await measureGateway(home, port);
      child = again.child;
      starts.push(again.startMs);
      await sleep(200);
    }
    const turnMs = await measureTurn(port);
    const searchMs = await measureSearch(QUICK ? 5 : 25);
    const { docsMs, docsKb } = await measureDocs(QUICK ? 2 : 5);
    const { roomWriteMs, outboxDrainMs, telegramPollMs } = await measureLoops();
    const bench = {
      measuredAt: new Date().toISOString().slice(0, 10),
      node: process.version,
      installMs: measureInstall(),
      coldStartMs: median(coldStarts),
      idleRssMb: idleRss,
      // "stop and start again" — with a single sample we can only honestly report
      // the start half, so that is what goes in the table.
      restartMs: stops.length ? median(stops) + median(starts) : startMs,
      turnMs,
      searchMs,
      docsMs,
      docsKb,
      roomWriteMs,
      outboxDrainMs,
      telegramPollMs,
      ...(FIRST_RUN ? { ...measureFirstRun(), ...measureColdCheckout() } : {}),
      tolerancePct: TOLERANCE_PCT,
      budget: checkBudgets({
        installMs: 0,
        coldStartMs: 0,
        idleRssMb: 0,
        restartMs: 0,
        turnMs: 0,
      }).map((b) => ({ key: b.key, max: b.max, why: b.why })),
    };
    const budget = checkBudgets(bench).filter((b) => typeof b.value === 'number');
    bench.overBudget = budget.filter((b) => !b.ok).map((b) => b.key);
    if (WRITE) {
      const wrote = writeReadme(bench);
      if (!AS_JSON) console.log(wrote ? 'bench: README.md block refreshed' : 'bench: README.md already up to date');
    }
    if (AS_JSON) {
      console.log(JSON.stringify(bench, null, 2));
    } else if (!WRITE) {
      console.log(renderBlock(bench).split('\n').slice(1, -1).join('\n'));
    }
    if (BUDGET) {
      // --json keeps stdout parseable: the per-metric lines go to stderr there.
      const sink = AS_JSON ? console.error : console.log;
      for (const b of budget) {
        sink(`bench: ${b.ok ? 'ok  ' : 'OVER'} ${b.key} ${b.value} / ${b.max}${b.ok ? '' : ` - ${b.why}`}`);
      }
      if (bench.overBudget.length) {
        console.error(`bench: over budget: ${bench.overBudget.join(', ')} - see docs/PERFORMANCE.md`);
        process.exitCode = 1;
      } else if (!AS_JSON) {
        console.log(`bench: within budget (${budget.length}/${budget.length})`);
      }
    }
  } finally {
    if (child) await stopGateway(child, port);
    fs.rmSync(home, { recursive: true, force: true });
  }
}

// Importable: test/tier3i.test.ts pulls in checkBudgets to test the alarm itself
// (a fabricated over-budget number must be reported as over). Only run the
// measurements when this file *is* the program.
if (process.argv[1] && path.resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  main().catch((err) => {
    console.error(`bench failed: ${err instanceof Error ? err.message : String(err)}`);
    process.exit(1);
  });
}
