#!/usr/bin/env node
/**
 * docs-map.mjs — generate (and check) the file map in docs/ARCHITECTURE.md.
 *
 * The census row "Docs that match the code" stayed PARTIAL because the tree in
 * ARCHITECTURE.md was hand-written: it named `gemini.ts`, `anthropic.ts` and
 * `ollama.ts`, and none of those files has ever existed. A hand-written map of a
 * moving tree is a promise nobody can keep, so the map is generated from disk:
 *
 *   node scripts/docs-map.mjs --write   # refresh the block in docs/ARCHITECTURE.md
 *   node scripts/docs-map.mjs --check   # exit 1 if it is stale (the suite runs this)
 *
 * Descriptions are carried over from the previous block, so editing code never
 * loses a human sentence. A file with no description is marked
 * `*(new — describe me)*`: visible in the doc, and the check fails until somebody
 * writes one. That is the point — the doc cannot drift silently.
 */
import fs from 'node:fs';
import path from 'node:path';

const ROOT = path.resolve(import.meta.dirname, '..');
const DOC = path.join(ROOT, 'docs', 'ARCHITECTURE.md');
const BEGIN = '<!-- BEGIN DOCS MAP (generated by scripts/docs-map.mjs) -->';
const END = '<!-- END DOCS MAP -->';
const NEW_FILE_NOTE = '*(new — describe me)*';

/** Every .ts file under src/, as repo-relative posix paths, sorted. */
function srcFiles(dir = path.join(ROOT, 'src'), out = []) {
  for (const e of fs.readdirSync(dir, { withFileTypes: true }).sort((a, b) => a.name.localeCompare(b.name))) {
    const full = path.join(dir, e.name);
    if (e.isDirectory()) srcFiles(full, out);
    else if (e.name.endsWith('.ts')) out.push(path.relative(ROOT, full).split(path.sep).join('/'));
  }
  return out;
}

/** The first sentence of a file's leading comment — generated prose, from the code itself. */
function leadingComment(rel) {
  let raw;
  try {
    raw = fs.readFileSync(path.join(ROOT, rel), 'utf8');
  } catch {
    return undefined;
  }
  const head = raw.slice(0, 900);
  const block = /\/\*\*?([\s\S]*?)\*\//.exec(head);
  let text = '';
  if (block && block.index < 300) text = block[1];
  else {
    const lines = head.split('\n').filter((l) => l.trimStart().startsWith('//'));
    if (lines.length) text = lines.map((l) => l.trimStart().replace(/^\/\/\s?/, '')).join(' ');
  }
  if (!text) return undefined;
  const flat = text
    .split('\n')
    .map((l) => l.replace(/^\s*\*\s?/, '').trim())
    .filter(Boolean)
    .join(' ')
    .replace(/\s+/g, ' ')
    .trim();
  if (!flat) return undefined;
  const first = /^(.{20,160}?[.!?])(\s|$)/.exec(flat);
  const cut = (first ? first[1] : flat).replace(/[.]+$/, '');
  return cut.length > 160 ? `${cut.slice(0, 157)}…` : cut;
}

/** Descriptions already written in the generated block (file -> sentence). */
function blockDescriptions(doc) {
  const out = new Map();
  const a = doc.indexOf(BEGIN);
  const b = doc.indexOf(END);
  if (a < 0 || b < 0) return out;
  for (const line of doc.slice(a, b).split('\n')) {
    const m = /^\|\s*`([^`]+)`\s*\|\s*(.*?)\s*\|\s*$/.exec(line);
    // Un-escape what renderMap escapes, or every `--write` would add another
    // layer of backslashes to a description that contains a pipe (fixed 33.4).
    if (m && m[2] && m[2] !== NEW_FILE_NOTE) out.set(m[1], m[2].replace(/\\+\|/g, '|'));
  }
  return out;
}

/** The `path.ts  # what it does` lines of a component map (prose or a previous tree). */
function annotatedDescriptions(doc) {
  const out = new Map();
  for (const line of doc.split('\n')) {
    const m = /(?:^|[\s│├└─])((?:[A-Za-z0-9_-]+\/)*[A-Za-z0-9_-]+\.ts)\s+#\s*(.+)/.exec(line);
    if (!m) continue;
    const key = m[1];
    const value = m[2].replace(/\s+/g, ' ').trim();
    if (!out.has(key)) out.set(key, value);
  }
  const bySuffix = [...out.entries()];
  return (full) => {
    const hit = bySuffix.find(([key]) => full === key || full.endsWith(`/${key}`));
    return hit ? hit[1] : undefined;
  };
}

/** The markdown table, generated from disk + whatever descriptions we can find. */
export function renderMap(doc) {
  const known = blockDescriptions(doc);
  const annotated = annotatedDescriptions(doc);
  const rows = srcFiles().map((file) => {
    const desc = known.get(file) ?? annotated(file) ?? leadingComment(file) ?? NEW_FILE_NOTE;
    return `| \`${file}\` | ${desc.replace(/\|/g, '\\|')} |`;
  });
  return ['| file | what it does |', '|---|---|', ...rows].join('\n');
}

function main() {
  const arg = process.argv[2];
  const doc = fs.readFileSync(DOC, 'utf8');
  const a = doc.indexOf(BEGIN);
  const b = doc.indexOf(END);
  const markers = a >= 0 && b >= 0;

  if (arg === '--write') {
    const block = `${BEGIN}\n\n${renderMap(doc)}\n\n${END}`;
    const next = markers ? doc.slice(0, a) + block + doc.slice(b + END.length) : `${doc.trimEnd()}\n\n## File map\n\n${block}\n`;
    if (next === doc) return console.log('docs-map: already up to date');
    fs.writeFileSync(DOC, next, 'utf8');
    console.log(`docs-map: wrote ${srcFiles().length} file(s) into docs/ARCHITECTURE.md`);
    return;
  }

  if (arg === '--check') {
    if (!markers) {
      console.error('docs-map: markers missing in docs/ARCHITECTURE.md — run: node scripts/docs-map.mjs --write');
      process.exit(1);
    }
    // The contract: every .ts file under src/ is listed, and none is undescribed.
    const listed = new Set(
      doc
        .slice(a, b)
        .split('\n')
        .map((l) => /^\|\s*`([^`]+)`\s*\|/.exec(l)?.[1])
        .filter(Boolean),
    );
    const onDisk = srcFiles();
    const missing = onDisk.filter((f) => !listed.has(f));
    const extra = [...listed].filter((f) => !onDisk.includes(f));
    const undescribed = onDisk.filter((f) => !blockDescriptions(doc).has(f) && !annotatedDescriptions(doc)(f) && !leadingComment(f));
    // A row that still says "new — describe me" while the file *has* a header
    // comment is drift too: the check used to pass here, because it looked at
    // the source for a description instead of at the row. The doc is what a
    // reader sees, so the placeholder has to count.
    const placeholders = [...doc.slice(a, b).matchAll(/^\|\s*`([^`]+)`\s*\|\s*\*\(new — describe me\)\*\s*\|/gm)]
      .map((m) => m[1])
      .filter((f) => Boolean(leadingComment(f)) || Boolean(annotatedDescriptions(doc)(f)));
    if (missing.length || extra.length || undescribed.length || placeholders.length) {
      const why = [];
      if (missing.length) why.push(`${missing.length} file(s) missing (${missing.slice(0, 3).join(', ')}${missing.length > 3 ? ', …' : ''})`);
      if (extra.length) why.push(`${extra.length} listed but not on disk (${extra.slice(0, 3).join(', ')})`);
      if (undescribed.length) why.push(`${undescribed.length} with no description (${undescribed.slice(0, 3).join(', ')})`);
      if (placeholders.length) why.push(`${placeholders.length} row(s) still say "describe me" although a description exists (${placeholders.slice(0, 3).join(', ')})`);
      console.error(`docs-map: docs/ARCHITECTURE.md drifted — ${why.join('; ')} — run: node scripts/docs-map.mjs --write`);
      process.exit(1);
    }
    console.log(`docs-map: ok (${onDisk.length} files under src/ are listed and described in docs/ARCHITECTURE.md)`);
    return;
  }

  console.log('usage: node scripts/docs-map.mjs --write|--check');
  if (arg) process.exit(1);
}

main();
