#!/usr/bin/env node
/**
 * 38.3 — the suite has a clock.
 *
 * "The tests got slow" is a feeling until somebody measures it, and a suite
 * that takes fifteen minutes is a suite people stop running — which is how a
 * project ends up with tests that do not run at all. This script runs the whole
 * suite once with a reporter that records **per file** time, writes the result
 * to `docs/openclaw/data/suite-time.json`, names the slowest files in
 * `docs/TESTING.md`, and refuses (exit 1) when the run crosses its budget.
 *
 *   node scripts/suite-time.mjs --run     # measure: run the suite, record, report
 *   node scripts/suite-time.mjs --check   # is the recorded run inside budget?
 *   node scripts/suite-time.mjs --json    # the recorded run, machine-readable
 *
 * The same file is the reporter node's test runner loads (`--test-reporter`),
 * which is why there is no second script to keep in sync: when node imports
 * this module it only sees the async generator below, and `main()` stays quiet.
 */
import fs from 'node:fs';
import path from 'node:path';
import { execFileSync } from 'node:child_process';
import { fileURLToPath } from 'node:url';

const ROOT = path.resolve(import.meta.dirname, '..');
const SELF = fileURLToPath(import.meta.url);
const BEGIN = '<!-- BEGIN SUITE TIME (generated by scripts/suite-time.mjs) -->';
const END = '<!-- END SUITE TIME -->';

/**
 * The budget (38.3). Wall clock is measured here on a 2-vCPU box: ~90 s for the
 * whole suite. A phone is slower, and that is what the --timeout flag is for;
 * these ceilings are the alarm for *this* machine, like every other budget in
 * docs/PERFORMANCE.md.
 */
export const SUITE_BUDGETS = {
  wallMs: { max: 240_000, why: 'the whole run, on the machine that runs it' },
  fileMs: { max: 90_000, why: 'no single file may dominate the run' },
};

/** Where the measurement lives; overridable for tests. */
export function suiteTimePath() {
  return process.env.TCRAB_SUITE_TIME || path.join(ROOT, 'docs', 'openclaw', 'data', 'suite-time.json');
}

/** The doc that carries the slowest files; overridable for tests. */
export function suiteDocPath() {
  return process.env.TCRAB_SUITE_DOC || path.join(ROOT, 'docs', 'TESTING.md');
}

/** Turn raw test events into one row per file. Exported so a test can drive it. */
export function summarizeEvents(events) {
  const byFile = new Map();
  for (const ev of events) {
    const file = typeof ev.file === 'string' ? ev.file : '';
    if (!file) continue;
    const row = byFile.get(file) ?? { file: path.basename(file), ms: 0, cases: 0, passed: 0, skipped: 0, topTests: 0, fail: 0, slowest: { name: '', ms: 0 } };
    // Every pass/fail event is a test case (subtests included) — the same thing
    // the coverage report counts. A skipped test arrives as test:pass with
    // skip:true (42.1: the tracker quotes pass/fail/skip from the record, so the
    // record has to carry them, not just the total).
    row.cases += 1;
    if (ev.status === 'fail') row.failed = (row.failed ?? 0) + 1;
    else if (ev.skipped) row.skipped += 1;
    else row.passed += 1;
    if (Number(ev.nesting) === 0) {
      // Within a file the top-level tests run one after another, so their
      // durations add up to the file's test time; a nested test's duration is
      // already inside its parent's number, and its failure is reported by the
      // parent too, so only top-level tests are counted for time and failures.
      row.topTests += 1;
      row.ms += Number(ev.ms) || 0;
      if (ev.status === 'fail') row.fail += 1;
      if ((Number(ev.ms) || 0) > row.slowest.ms) row.slowest = { name: String(ev.name ?? ''), ms: Number(ev.ms) || 0 };
    }
    byFile.set(file, row);
  }
  return [...byFile.values()].sort((a, b) => b.ms - a.ms);
}

/** Read the events file the reporter wrote (one JSON object per line). */
export function readEvents(file) {
  let raw = '';
  try {
    raw = fs.readFileSync(file, 'utf8');
  } catch {
    return [];
  }
  const events = [];
  for (const line of raw.split('\n')) {
    if (!line.trim()) continue;
    try {
      events.push(JSON.parse(line));
    } catch {
      /* a torn line is dropped, like every other JSONL reader here */
    }
  }
  return events;
}

/** The record: what the suite cost, file by file, against the budget. */
export function buildRecord({ wallMs, events, node = process.version }) {
  const files = summarizeEvents(events);
  const over = [];
  if (wallMs > SUITE_BUDGETS.wallMs.max) over.push('wallMs');
  for (const f of files) if (f.ms > SUITE_BUDGETS.fileMs.max) over.push(f.file);
  const totalTests = files.reduce((n, f) => n + f.cases, 0);
  const totalTop = files.reduce((n, f) => n + f.topTests, 0);
  const totalPass = files.reduce((n, f) => n + f.passed, 0);
  const totalSkipped = files.reduce((n, f) => n + f.skipped, 0);
  const totalFail = totalTests - totalPass - totalSkipped;
  return {
    at: new Date().toISOString(),
    node,
    wallMs: Math.round(wallMs),
    totalFiles: files.length,
    totalTests,
    totalTopTests: totalTop,
    totalPass,
    totalFail,
    totalSkipped,
    slowest: files.slice(0, 5).map((f) => ({ file: f.file, ms: Math.round(f.ms) })),
    files: files.map((f) => ({
      file: f.file,
      ms: Math.round(f.ms),
      cases: f.cases,
      passed: f.passed,
      skipped: f.skipped,
      topTests: f.topTests,
      fail: f.fail,
      slowest: { name: f.slowest.name, ms: Math.round(f.slowest.ms) },
    })),
    budget: { wallMs: SUITE_BUDGETS.wallMs.max, fileMs: SUITE_BUDGETS.fileMs.max },
    over,
  };
}

/** What the recorded run says, without running anything. */
export function readSuiteTime(file = suiteTimePath()) {
  try {
    const parsed = JSON.parse(fs.readFileSync(file, 'utf8'));
    return parsed && typeof parsed === 'object' && Array.isArray(parsed.files) ? parsed : null;
  } catch {
    return null;
  }
}

/** The generated block of docs/TESTING.md: the slowest files, by name. */
export function renderDocBlock(record) {
  const rows = record.slowest.map((f) => `| \`${f.file}\` | ${(f.ms / 1000).toFixed(1)} s |`);
  return [
    BEGIN,
    '',
    `_Measured ${String(record.at).slice(0, 10)} on node ${record.node} — \`node scripts/suite-time.mjs --run\` re-measures, \`--check\` fails when the run is over its budget._`,
    '',
    `The whole suite: **${record.totalFiles} files, ${record.totalTests} test cases, ${(record.wallMs / 1000).toFixed(1)} s** (budget ${(record.budget.wallMs / 1000).toFixed(0)} s; no file may take more than ${(record.budget.fileMs / 1000).toFixed(0)} s). Each row is the sum of that file's top-level tests, so the numbers add up to roughly the wall clock.`,
    '',
    '| slowest file | time |',
    '|---|---|',
    ...rows,
    '',
    END,
  ].join('\n');
}

/** Write the block into the doc, replacing the previous one. */
export function writeDoc(record, file = suiteDocPath()) {
  const doc = fs.readFileSync(file, 'utf8');
  const a = doc.indexOf(BEGIN);
  const b = doc.indexOf(END);
  const block = renderDocBlock(record);
  const next = a >= 0 && b >= 0 ? doc.slice(0, a) + block + doc.slice(b + END.length) : `${doc.trimEnd()}\n\n${block}\n`;
  if (next !== doc) fs.writeFileSync(file, next, 'utf8');
  return file;
}

/** The reporter node's runner loads; silent, and writes events when asked to. */
export default async function* suiteReporter(source) {
  const eventsFile = process.env.TCRAB_SUITE_EVENTS;
  for await (const ev of source) {
    if (!eventsFile) continue;
    if (ev.type !== 'test:pass' && ev.type !== 'test:fail') continue;
    const data = ev.data ?? {};
    fs.appendFileSync(
      eventsFile,
      `${JSON.stringify({
        file: data.file,
        name: data.name,
        nesting: data.nesting,
        ms: data.details?.duration_ms ?? 0,
        status: ev.type === 'test:fail' ? 'fail' : 'pass',
        skipped: Boolean(data.skip ?? data.todo),
      })}\n`,
    );
  }
}

function runSuite() {
  const dir = path.join(ROOT, 'dist', 'test');
  const files = fs
    .readdirSync(dir)
    .filter((f) => f.endsWith('.test.js'))
    .sort()
    .map((f) => path.join(dir, f));
  const eventsFile = path.join(fs.mkdtempSync(path.join(process.env.TMPDIR || '/tmp', 'tsuite-')), 'events.jsonl');
  const started = Date.now();
  let code = 0;
  try {
    execFileSync(
      process.execPath,
      ['--test', '--test-timeout=60000', `--test-reporter=${SELF}`, ...files],
      { cwd: ROOT, env: { ...process.env, TCRAB_SUITE_EVENTS: eventsFile }, stdio: ['ignore', 'inherit', 'inherit'] },
    );
  } catch (err) {
    code = (err && typeof err === 'object' && 'status' in err ? Number(err.status) : 1) || 1;
  }
  const wallMs = Date.now() - started;
  const record = buildRecord({ wallMs, events: readEvents(eventsFile) });
  fs.mkdirSync(path.dirname(suiteTimePath()), { recursive: true });
  fs.writeFileSync(suiteTimePath(), `${JSON.stringify(record, null, 2)}\n`, 'utf8');
  writeDoc(record);
  return { record, code };
}

function main() {
  const args = process.argv.slice(2);
  const asJson = args.includes('--json');
  const check = args.includes('--check');

  if (check) {
    const record = readSuiteTime();
    if (!record) {
      console.error(`suite-time: no record at ${suiteTimePath()} — run: node scripts/suite-time.mjs --run`);
      process.exit(1);
    }
    const over = record.over ?? [];
    if (asJson) {
      console.log(JSON.stringify(record, null, 2));
    } else {
      console.log(
        `suite-time: ${record.totalFiles} files, ${record.totalTests} test cases in ${(record.wallMs / 1000).toFixed(1)} s ` +
          `(budget ${(record.budget.wallMs / 1000).toFixed(0)} s) — slowest ${record.slowest.map((f) => `${f.file} ${(f.ms / 1000).toFixed(1)}s`).join(', ')}`,
      );
    }
    if (over.length) {
      console.error(`suite-time: over budget: ${over.join(', ')}`);
      process.exit(1);
    }
    // Staleness is information, not a failure: a test file edited after the
    // record only means the next --run will move the numbers.
    const newest = newestTestMs();
    if (newest && Date.parse(record.at) < newest) {
      console.log(`suite-time: note — a test file changed after this record; re-run to refresh it`);
    }
    return;
  }

  const { record, code } = runSuite();
  if (asJson) console.log(JSON.stringify(record, null, 2));
  else {
    console.log('');
    console.log(`  🕐 suite in ${(record.wallMs / 1000).toFixed(1)} s over ${record.totalFiles} files (${record.totalTests} test cases) — budget ${(record.budget.wallMs / 1000).toFixed(0)} s`);
    for (const f of record.slowest) console.log(`     ${String((f.ms / 1000).toFixed(1)).padStart(6)} s  ${f.file}`);
    console.log(`     record: ${suiteTimePath()}`);
    if (record.over.length) console.log(`     ⚠️ over budget: ${record.over.join(', ')}`);
  }
  if (code !== 0) process.exitCode = code;
  if (record.over.length) process.exitCode = 1;
}

/** Newest mtime under dist/test, in ms — what "the record is stale" means. */
function newestTestMs() {
  let newest = 0;
  try {
    for (const f of fs.readdirSync(path.join(ROOT, 'dist', 'test'))) {
      if (!f.endsWith('.test.js')) continue;
      newest = Math.max(newest, fs.statSync(path.join(ROOT, 'dist', 'test', f)).mtimeMs);
    }
  } catch {
    /* no dist yet */
  }
  return newest;
}

if (process.argv[1] && path.resolve(process.argv[1]) === SELF) main();
